import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sofiia`s authors',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {children}
      </div>
    </main>
  );
}
